services:
  postgres:
    image: postgres:15-alpine
    container_name: aws-cognito
    environment:
      POSTGRES_DB: cognito
      POSTGRES_USER: cognito
      POSTGRES_PASSWORD: cognito
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
